# docker-compose.yml

services:
  shxl-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.api.app
      - FLASK_ENV=development
      - PYTHONPATH=/app
    networks:
      - shxl-network

  # Servicio opcional para testing
  shxl-test:
    build: .
    profiles:
      - testing
    depends_on:
      - shxl-backend
    volumes:
      - ./src/api/test:/app/test
    networks:
      - shxl-network
    command: ["bash", "/app/test/test_game_flow.sh"]
    environment:
      - BASE_URL=http://shxl-backend:5000

networks:
  shxl-network:
    driver: bridge
